language: java
arch:
  - amd64
#  - ppc64le
jdk: openjdk11
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
script:
  - conda install -c beakerx beakerx_kernel_java
  - conda install -c beakerx beakerx_kernel_autotranslation
  - conda install -c beakerx beakerx_tabledisplay
  - conda install -c beakerx beakerx_widgets
